### H2 Configuration
spring:
  h2:
    console:
      enabled: true
      path: /person-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:person-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: password
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
## H2 Configuration